'use client'

import { useState, useEffect } from 'react'

export default function AiAdminPage() {
    const [configs, setConfigs] = useState<any[]>([])
    const [npcs, setNpcs] = useState<any[]>([])
    const [frontDesks, setFrontDesks] = useState<any[]>([])
    const [status, setStatus] = useState('')
    const [isLoading, setIsLoading] = useState(true)
    const [isTesting, setIsTesting] = useState<string | null>(null)
    const [testResults, setTestResults] = useState<Record<string, { success: boolean; message: string }>>({})
    const [usageStats, setUsageStats] = useState<any>(null)
    const [activeTab, setActiveTab] = useState<'npcs' | 'frontDesks'>('npcs')

    useEffect(() => {
        fetchInitialData()
    }, [])

    const fetchInitialData = async () => {
        setIsLoading(true)
        try {
            const [npcsRes, desksRes, configsRes, usageRes] = await Promise.all([
                fetch('/api/ai/npcs'),
                fetch('/api/front-desk'),
                fetch('/api/admin/ai/config'),
                fetch('/api/admin/ai/usage')
            ])

            const npcsData = await npcsRes.json()
            if (npcsData.success) setNpcs(npcsData.data)

            const desksData = await desksRes.json()
            if (desksData.success) setFrontDesks(desksData.data)

            if (configsRes.ok) {
                const configsData = await configsRes.json()
                if (configsData.success) {
                    setConfigs(configsData.data || [])
                }
            }

            if (usageRes.ok) {
                const usageData = await usageRes.json()
                if (usageData.success) {
                    setUsageStats(usageData)
                }
            }
        } catch (e) {
            console.error('Fetch error:', e)
        } finally {
            setIsLoading(false)
        }
    }

    const addNewConfig = () => {
        const newConfig = {
            id: '', // Will be generated by backend
            provider: 'openai',
            apiKey: '',
            modelName: 'gpt-4o-mini',
            baseUrl: 'https://api.openai.com/v1',
            temperature: 0.7,
            dailyLimit: 20,
            isActive: true,
            isNew: true
        }
        setConfigs([newConfig, ...configs])
    }

    const handleConfigChange = (index: number, field: string, value: any) => {
        const newConfigs = [...configs]
        newConfigs[index] = { ...newConfigs[index], [field]: value }

        // Auto-fill defaults when provider changes
        if (field === 'provider') {
            const p = value;
            if (p === 'deepseek') {
                newConfigs[index].modelName = 'deepseek-chat';
                newConfigs[index].baseUrl = 'https://api.deepseek.com';
            } else if (p === 'siliconflow') {
                newConfigs[index].modelName = 'deepseek-ai/DeepSeek-V3';
                newConfigs[index].baseUrl = 'https://api.siliconflow.cn/v1';
            } else if (p === 'gemini') {
                newConfigs[index].modelName = 'gemini-1.5-flash';
                newConfigs[index].baseUrl = '';
            } else if (p === 'openai') {
                newConfigs[index].modelName = 'gpt-4o-mini';
                newConfigs[index].baseUrl = 'https://api.openai.com/v1';
            }
        }

        setConfigs(newConfigs)
    }

    const saveConfig = async (config: any, index: number) => {
        setStatus(`正在保存 ${config.provider} 配置...`)
        try {
            const res = await fetch('/api/admin/ai/config', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(config)
            })
            if (res.ok) {
                const data = await res.json()
                setStatus(`✅ ${config.provider} 配置已更新`)
                const newConfigs = [...configs]
                newConfigs[index] = data.data
                setConfigs(newConfigs)
            } else {
                setStatus('❌ 保存失败')
            }
        } catch (e) {
            setStatus('❌ 网络错误')
        }
        setTimeout(() => setStatus(''), 3000)
    }

    const deleteConfig = async (id: string, index: number) => {
        if (!id) {
            // Just remove from UI if it was a new unsaved config
            setConfigs(configs.filter((_, i) => i !== index))
            return
        }

        if (!confirm('确定要删除这个 AI 配置吗？所有使用此 Token 的 NPC 将受到影响。')) return

        setStatus('正在删除配置...')
        try {
            const res = await fetch(`/api/admin/ai/config?id=${id}`, {
                method: 'DELETE'
            })
            if (res.ok) {
                setStatus('✅ 配置已删除')
                setConfigs(configs.filter((_, i) => i !== index))
            } else {
                setStatus('❌ 删除失败')
            }
        } catch (e) {
            setStatus('❌ 网络错误')
        }
        setTimeout(() => setStatus(''), 3000)
    }

    const testAi = async (config: any, index: number) => {
        const testId = config.id || `test-${index}`
        setIsTesting(testId)
        setTestResults(prev => ({ ...prev, [testId]: { success: false, message: '正在连接...' } }))

        try {
            const res = await fetch('/api/admin/ai/test', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(config)
            })
            const data = await res.json()
            if (data.success) {
                setTestResults(prev => ({ ...prev, [testId]: { success: true, message: `连接成功！AI 回复: ${data.reply}` } }))
            } else {
                setTestResults(prev => ({ ...prev, [testId]: { success: false, message: `连接失败: ${data.error}` } }))
            }
        } catch (e) {
            setTestResults(prev => ({ ...prev, [testId]: { success: false, message: '网络错误，无法连接到测试接口' } }))
        } finally {
            setIsTesting(null)
        }
    }

    const saveNpc = async (npc: any) => {
        setStatus(`正在保存 ${npc.name}...`)
        try {
            const res = await fetch(`/api/ai/npcs/${npc.id}`, {
                method: 'PUT',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(npc)
            })
            if (res.ok) setStatus(`✅ ${npc.name} 已更新`)
            else setStatus('❌ 保存失败')
        } catch (e) {
            setStatus('❌ 网络错误')
        }
        setTimeout(() => setStatus(''), 3000)
    }

    const handleNpcChange = (id: string, field: string, value: any) => {
        setNpcs(prev => prev.map(n => n.id === id ? { ...n, [field]: value } : n))
    }

    const handleDeskChange = (id: string, field: string, value: any) => {
        setFrontDesks(prev => prev.map(d => d.id === id ? { ...d, [field]: value } : d))
    }

    const saveDesk = async (desk: any) => {
        setStatus(`正在保存 ${desk.name}...`)
        try {
            const res = await fetch(`/api/front-desk/${desk.id}`, {
                method: 'PUT',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(desk)
            })
            if (res.ok) setStatus(`✅ ${desk.name} 已更新`)
            else setStatus('❌ 保存失败')
        } catch (e) {
            setStatus('❌ 网络错误')
        }
        setTimeout(() => setStatus(''), 3000)
    }

    const syncNpcs = async () => {
        setStatus('正在同步灵魂数据...')
        try {
            const res = await fetch('/api/ai/npcs?force=true')
            const data = await res.json()
            if (data.success) {
                setNpcs(data.data)
                setStatus('✅ 全员数据已重置并同步')
            }
        } catch (e) {
            setStatus('❌ 同步失败')
        }
        setTimeout(() => setStatus(''), 3000)
    }

    if (isLoading) return <div className="p-8 font-mono text-cyan-500">SYSTEM INITIALIZING...</div>

    return (
        <div className="p-8 max-w-5xl mx-auto space-y-8">
            <div className="flex justify-between items-end border-b border-gray-800 pb-4">
                <div>
                    <h1 className="text-3xl font-bold text-white tracking-tight">AI NPC 集成控制台</h1>
                    <p className="text-gray-400 mt-2">管理多模型 AI 轮询池及各 NPC 的灵魂设定</p>
                </div>
                <div className="text-right">
                    <span className="text-[10px] font-mono text-gray-600 block">LAST SYNC: {new Date().toLocaleTimeString()}</span>
                    <span className="text-xs text-green-500 font-mono flex items-center justify-end gap-1">
                        <span className="w-1.5 h-1.5 bg-green-500 rounded-full animate-pulse"></span>
                        BACKEND_READY
                    </span>
                </div>
            </div>

            {/* AI Config Pool Section */}
            <section className="space-y-4">
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-purple-600/20 rounded-xl flex items-center justify-center text-purple-400 border border-purple-500/30">
                            ⚡
                        </div>
                        <h2 className="text-xl font-bold text-gray-100">核心 AI 算力池 (模型轮询)</h2>
                    </div>
                    <button
                        onClick={addNewConfig}
                        className="bg-purple-600 hover:bg-purple-500 text-white text-xs font-bold py-2 px-4 rounded-lg transition-all flex items-center gap-2"
                    >
                        <span>+</span> 添加新供应商/模型
                    </button>
                </div>

                {configs.length === 0 && (
                    <div className="bg-gray-900/50 border border-dashed border-gray-800 rounded-2xl p-12 text-center">
                        <p className="text-gray-500">尚未配置任何 AI 供应商。点击右上角按钮开始添加。</p>
                    </div>
                )}

                <div className="space-y-4">
                    {configs.map((config, index) => {
                        const testId = config.id || `test-${index}`
                        const testResult = testResults[testId]
                        return (
                            <div key={config.id || `new-${index}`} className={`bg-gray-900/50 rounded-2xl border ${config.isActive ? 'border-gray-800' : 'border-red-900/30 opacity-60'} p-6 shadow-xl backdrop-blur-sm transition-all`}>
                                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                                    <div className="space-y-4">
                                        <div className="space-y-2">
                                            <label className="text-[10px] font-mono text-gray-500 uppercase">供应商 (Provider)</label>
                                            <select
                                                className="w-full bg-gray-950 border border-gray-800 rounded-xl p-2.5 text-sm text-gray-200 focus:border-purple-500 outline-none"
                                                value={config.provider}
                                                onChange={e => handleConfigChange(index, 'provider', e.target.value)}
                                            >
                                                <option value="gemini">Google Gemini</option>
                                                <option value="openai">OpenAI / Claude</option>
                                                <option value="deepseek">DeepSeek (Official)</option>
                                                <option value="siliconflow">SiliconFlow (R1/V3)</option>
                                            </select>
                                        </div>
                                        <div className="space-y-2">
                                            <label className="text-[10px] font-mono text-gray-500 uppercase">状态 (Status)</label>
                                            <div className="flex items-center gap-2">
                                                <input
                                                    type="checkbox"
                                                    id={`active-${testId}`}
                                                    checked={config.isActive}
                                                    onChange={e => handleConfigChange(index, 'isActive', e.target.checked)}
                                                    className="w-4 h-4 accent-purple-500"
                                                />
                                                <label htmlFor={`active-${testId}`} className="text-xs text-gray-400">启用此模型到轮询池</label>
                                            </div>
                                        </div>
                                    </div>

                                    <div className="md:col-span-2 grid grid-cols-1 sm:grid-cols-2 gap-4">
                                        <div className="space-y-2">
                                            <label className="text-[10px] font-mono text-gray-500 uppercase">模型名称 (Model Identifier)</label>
                                            <input
                                                type="text"
                                                className="w-full bg-gray-950 border border-gray-800 rounded-xl p-2.5 text-sm text-gray-200 focus:border-purple-500 outline-none"
                                                value={config.modelName}
                                                onChange={e => handleConfigChange(index, 'modelName', e.target.value)}
                                            />
                                        </div>
                                        <div className="space-y-2">
                                            <label className="text-[10px] font-mono text-gray-500 uppercase">每日限制 (Hits/Day)</label>
                                            <input
                                                type="number"
                                                className="w-full bg-gray-950 border border-gray-800 rounded-xl p-2.5 text-sm text-yellow-500 font-bold focus:border-purple-500 outline-none"
                                                value={config.dailyLimit}
                                                onChange={e => handleConfigChange(index, 'dailyLimit', parseInt(e.target.value) || 0)}
                                            />
                                        </div>
                                        <div className="md:col-span-2 space-y-2">
                                            <label className="text-[10px] font-mono text-gray-500 uppercase">API Key</label>
                                            <input
                                                type="password"
                                                placeholder="sk-..."
                                                className="w-full bg-gray-950 border border-gray-800 rounded-xl p-2.5 text-sm text-cyan-100 font-mono focus:border-purple-500 outline-none"
                                                value={config.apiKey}
                                                onChange={e => handleConfigChange(index, 'apiKey', e.target.value)}
                                            />
                                        </div>
                                        <div className="md:col-span-2 space-y-2">
                                            <label className="text-[10px] font-mono text-gray-500 uppercase">Base URL (可选)</label>
                                            <input
                                                type="text"
                                                className="w-full bg-gray-950 border border-gray-800 rounded-xl p-2.5 text-sm text-gray-400 font-mono focus:border-purple-500 outline-none"
                                                value={config.baseUrl}
                                                onChange={e => handleConfigChange(index, 'baseUrl', e.target.value)}
                                            />
                                        </div>
                                    </div>
                                </div>

                                <div className="mt-6 flex items-center justify-between border-t border-gray-800/50 pt-4">
                                    <div className="flex-1">
                                        {testResult && (
                                            <p className={`text-[10px] font-mono ${testResult.success ? 'text-green-500' : 'text-red-500'}`}>
                                                {testResult.message}
                                            </p>
                                        )}
                                    </div>
                                    <div className="flex items-center gap-3">
                                        <button
                                            onClick={() => deleteConfig(config.id, index)}
                                            className="text-gray-500 hover:text-red-400 text-xs px-3 py-1.5 transition-colors"
                                        >
                                            删除
                                        </button>
                                        <button
                                            onClick={() => testAi(config, index)}
                                            disabled={isTesting === testId}
                                            className="bg-gray-800 hover:bg-gray-700 text-gray-300 text-xs py-1.5 px-4 rounded-lg border border-gray-700 disabled:opacity-50"
                                        >
                                            {isTesting === testId ? '测试中...' : '测试'}
                                        </button>
                                        <button
                                            onClick={() => saveConfig(config, index)}
                                            className="bg-purple-600/20 hover:bg-purple-600/40 text-purple-400 border border-purple-500/30 text-xs font-bold py-1.5 px-5 rounded-lg transition-all"
                                        >
                                            保存此配置
                                        </button>
                                    </div>
                                </div>
                            </div>
                        )
                    })}
                </div>
            </section>

            {/* Usage Stats Section */}
            {usageStats && usageStats.summary && (
                <section className="bg-gray-900/50 rounded-2xl border border-gray-800 p-6 shadow-2xl backdrop-blur-sm">
                    <div className="flex items-center gap-3 mb-6">
                        <div className="w-10 h-10 bg-cyan-600/20 rounded-xl flex items-center justify-center text-cyan-400 border border-cyan-500/30">
                            📊
                        </div>
                        <h2 className="text-xl font-bold text-gray-100">Token 消耗量化报告 (Daily Tokens)</h2>
                    </div>

                    <div className="overflow-x-auto">
                        <table className="w-full text-left font-mono text-xs">
                            <thead className="bg-gray-950/50 text-gray-500 uppercase">
                                <tr>
                                    <th className="px-4 py-3 rounded-l-lg">日期 (Date)</th>
                                    <th className="px-4 py-3">对话次数 (Hits)</th>
                                    <th className="px-4 py-3">用户数 (Users)</th>
                                    <th className="px-4 py-3">输入 (Prompt)</th>
                                    <th className="px-4 py-3">输出 (Completion)</th>
                                    <th className="px-4 py-3 rounded-r-lg">总计 (Total Tokens)</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-800">
                                {usageStats.summary.map((day: any) => (
                                    <tr key={day.date} className="hover:bg-gray-800/30 transition-colors">
                                        <td className="px-4 py-4 text-gray-300 font-bold">{day.date}</td>
                                        <td className="px-4 py-4 text-cyan-400">{day.totalCount}</td>
                                        <td className="px-4 py-4 text-purple-400">{day.userCount}</td>
                                        <td className="px-4 py-4 text-gray-500">{day.promptTokens.toLocaleString()}</td>
                                        <td className="px-4 py-4 text-gray-500">{day.completionTokens.toLocaleString()}</td>
                                        <td className="px-4 py-4">
                                            <span className="bg-cyan-500/10 text-cyan-300 px-2 py-1 rounded border border-cyan-500/20">
                                                {day.totalTokens.toLocaleString()}
                                            </span>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </section>
            )}

            {/* Tabs for NPCs and Front Desks */}
            <div className="flex gap-2 mb-6 border-b border-gray-800">
                <button
                    onClick={() => setActiveTab('npcs')}
                    className={`px-6 py-3 font-bold text-sm transition-all ${activeTab === 'npcs'
                            ? 'text-pink-400 border-b-2 border-pink-500'
                            : 'text-gray-500 hover:text-gray-300'
                        }`}
                >
                    NPC 管理
                </button>
                <button
                    onClick={() => setActiveTab('frontDesks')}
                    className={`px-6 py-3 font-bold text-sm transition-all ${activeTab === 'frontDesks'
                            ? 'text-cyan-400 border-b-2 border-cyan-500'
                            : 'text-gray-500 hover:text-gray-300'
                        }`}
                >
                    前台客服管理
                </button>
            </div>

            {/* NPCs List Section */}
            {activeTab === 'npcs' && (
                <div className="grid grid-cols-1 gap-6">
                    <div className="flex justify-between items-center">
                        <h2 className="text-xl font-bold flex items-center gap-3">
                            <div className="w-1.5 h-6 bg-pink-500 rounded-full"></div>
                            活跃 NPC 灵魂工程
                        </h2>
                        <button
                            onClick={syncNpcs}
                            className="text-[10px] text-pink-400 border border-pink-500/30 px-3 py-1.5 rounded-lg hover:bg-pink-500/10 transition-all font-mono uppercase tracking-tighter"
                        >
                            ↻ 强制同步全员 / 重置
                        </button>
                    </div>

                    {npcs.map(npc => (
                        <div key={npc.id} className="bg-gray-900/40 rounded-2xl border border-gray-800 p-6 space-y-6 hover:border-pink-500/30 transition-colors">
                            <div className="flex justify-between items-start">
                                <div className="flex gap-4">
                                    <div className="w-14 h-14 bg-gray-800 rounded-2xl border border-gray-700 flex items-center justify-center text-3xl shadow-inner">
                                        {npc.role === 'IT Support' ? '⌨️' : '💁‍♀️'}
                                    </div>
                                    <div>
                                        <div className="flex items-center gap-2">
                                            <input
                                                className="bg-transparent text-xl font-bold text-white border-b border-transparent focus:border-pink-500 outline-none"
                                                value={npc.name}
                                                onChange={e => handleNpcChange(npc.id, 'name', e.target.value)}
                                            />
                                            <span className="text-[10px] px-2 py-0.5 bg-pink-500/10 text-pink-400 border border-pink-500/20 rounded-full uppercase font-mono">
                                                NPC_ID: {npc.id.substring(0, 8)}...
                                            </span>
                                        </div>
                                        <input
                                            className="bg-transparent text-sm text-gray-400 w-full border-b border-transparent focus:border-gray-600 outline-none mt-1"
                                            value={npc.role || ''}
                                            placeholder="职位名称，如 IT 支援"
                                            onChange={e => handleNpcChange(npc.id, 'role', e.target.value)}
                                        />
                                    </div>
                                </div>
                                <button
                                    onClick={() => saveNpc(npc)}
                                    className="text-[10px] font-bold py-1.5 px-4 rounded-lg bg-gray-800 hover:bg-gray-700 text-gray-300 border border-gray-700 transition-all uppercase tracking-widest"
                                >
                                    同步
                                </button>
                            </div>

                            <div className="grid grid-cols-1 gap-4">
                                <div className="space-y-2">
                                    <label className="text-[10px] font-mono text-gray-500 uppercase">性格设定 (System Prompt)</label>
                                    <textarea
                                        className="w-full bg-gray-950 border border-gray-800 rounded-xl p-4 text-sm text-gray-300 h-28 focus:border-pink-500 outline-none transition-all placeholder:italic"
                                        placeholder="描述这个 NPC 的性格、语言风格、偏好..."
                                        value={npc.personality}
                                        onChange={e => handleNpcChange(npc.id, 'personality', e.target.value)}
                                    />
                                </div>

                                <div className="space-y-2">
                                    <label className="text-[10px] font-mono text-gray-500 uppercase">业务知识库 (Specific Knowledge)</label>
                                    <textarea
                                        className="w-full bg-gray-950 border border-gray-800 rounded-xl p-4 text-sm text-cyan-100/70 h-20 focus:border-cyan-500 outline-none transition-all"
                                        placeholder="输入 NPC 专有的知识（已具备实施工位/在线名单的只读权限）"
                                        value={npc.knowledge || ''}
                                        onChange={e => handleNpcChange(npc.id, 'knowledge', e.target.value)}
                                    />
                                </div>

                                <div className="space-y-2">
                                    <label className="text-[10px] font-mono text-gray-500 uppercase">初始招呼语 (Greeting Message)</label>
                                    <input
                                        className="w-full bg-gray-950 border border-gray-800 rounded-xl p-3 text-sm text-gray-400 focus:border-gray-600 outline-none"
                                        value={npc.greeting || ''}
                                        onChange={e => handleNpcChange(npc.id, 'greeting', e.target.value)}
                                    />
                                </div>

                                <div className="space-y-4 pt-4 border-t border-gray-800">
                                    <label className="text-[10px] font-mono text-gray-500 uppercase flex items-center gap-2">
                                        坐标与移动 (POSITION & MOBILITY)
                                        <span className="text-[9px] bg-cyan-500/10 text-cyan-400 px-1.5 py-0.5 rounded border border-cyan-500/20 lowercase font-normal italic">
                                            new_feature
                                        </span>
                                    </label>
                                    <div className="flex flex-wrap items-center gap-6 bg-gray-950/50 p-4 rounded-xl border border-gray-800/50">
                                        <div className="flex items-center gap-3">
                                            <input
                                                type="checkbox"
                                                id={`fixed-${npc.id}`}
                                                className="w-5 h-5 rounded-lg accent-pink-500 bg-gray-950 border border-gray-800 cursor-pointer"
                                                checked={npc.isFixed || false}
                                                onChange={e => handleNpcChange(npc.id, 'isFixed', e.target.checked)}
                                            />
                                            <label htmlFor={`fixed-${npc.id}`} className="text-sm text-gray-300 cursor-pointer font-medium">
                                                固定位置 (No Wandering)
                                            </label>
                                        </div>

                                        <div className="h-6 w-px bg-gray-800 mx-2 hidden sm:block"></div>

                                        <div className="flex items-center gap-4">
                                            <div className="flex items-center gap-2">
                                                <span className="text-xs font-mono text-gray-500">X:</span>
                                                <input
                                                    type="number"
                                                    className="w-24 bg-gray-950 border border-gray-800 rounded-lg p-2 text-sm text-cyan-400 font-mono focus:border-cyan-500 outline-none"
                                                    value={npc.x || 0}
                                                    onChange={e => handleNpcChange(npc.id, 'x', parseInt(e.target.value) || 0)}
                                                />
                                            </div>
                                            <div className="flex items-center gap-2">
                                                <span className="text-xs font-mono text-gray-500">Y:</span>
                                                <input
                                                    type="number"
                                                    className="w-24 bg-gray-950 border border-gray-800 rounded-lg p-2 text-sm text-cyan-400 font-mono focus:border-cyan-500 outline-none"
                                                    value={npc.y || 0}
                                                    onChange={e => handleNpcChange(npc.id, 'y', parseInt(e.target.value) || 0)}
                                                />
                                            </div>
                                        </div>

                                        <p className="text-[10px] text-gray-600 italic sm:ml-auto">
                                            * 开启固定后，NPC 将精准定位在该坐标并停止随机走动。
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            )}

            {/* Front Desks List Section */}
            {activeTab === 'frontDesks' && (
                <div className="grid grid-cols-1 gap-6">
                    <div className="flex justify-between items-center">
                        <h2 className="text-xl font-bold flex items-center gap-3">
                            <div className="w-1.5 h-6 bg-cyan-500 rounded-full"></div>
                            前台客服配置中心
                        </h2>
                        <button
                            onClick={syncNpcs}
                            className="text-[10px] text-cyan-400 border border-cyan-500/30 px-3 py-1.5 rounded-lg hover:bg-cyan-500/10 transition-all font-mono uppercase tracking-tighter"
                        >
                            ↻ 同步更新
                        </button>
                    </div>

                    {frontDesks.map(desk => (
                        <div key={desk.id} className="bg-gray-900/40 rounded-2xl border border-gray-800 p-6 space-y-6 hover:border-cyan-500/30 transition-colors">
                            <div className="flex justify-between items-start">
                                <div className="flex gap-4">
                                    <div className="w-14 h-14 bg-gray-800 rounded-2xl border border-gray-700 flex items-center justify-center text-3xl shadow-inner">
                                        🏢
                                    </div>
                                    <div>
                                        <div className="flex items-center gap-2">
                                            <input
                                                className="bg-transparent text-xl font-bold text-white border-b border-transparent focus:border-cyan-500 outline-none"
                                                value={desk.name}
                                                onChange={e => handleDeskChange(desk.id, 'name', e.target.value)}
                                            />
                                            <span className="text-[10px] px-2 py-0.5 bg-cyan-500/10 text-cyan-400 border border-cyan-500/20 rounded-full uppercase font-mono">
                                                DESK_ID: {desk.id.substring(0, 8)}...
                                            </span>
                                        </div>
                                        <input
                                            className="bg-transparent text-sm text-gray-400 w-full border-b border-transparent focus:border-gray-600 outline-none mt-1"
                                            value={desk.serviceScope || ''}
                                            placeholder="服务范围，如 投诉与建议"
                                            onChange={e => handleDeskChange(desk.id, 'serviceScope', e.target.value)}
                                        />
                                    </div>
                                </div>
                                <button
                                    onClick={() => saveDesk(desk)}
                                    className="text-[10px] font-bold py-1.5 px-4 rounded-lg bg-gray-800 hover:bg-gray-700 text-gray-300 border border-gray-700 transition-all uppercase tracking-widest"
                                >
                                    同步
                                </button>
                            </div>

                            <div className="grid grid-cols-1 gap-4">
                                <div className="space-y-2">
                                    <label className="text-[10px] font-mono text-gray-500 uppercase">系统提示词 (System Prompt)</label>
                                    <textarea
                                        className="w-full bg-gray-950 border border-gray-800 rounded-xl p-4 text-sm text-gray-300 h-32 focus:border-cyan-500 outline-none transition-all placeholder:italic"
                                        placeholder="定义这个前台客服的角色、职责、回复风格..."
                                        value={desk.systemPrompt || ''}
                                        onChange={e => handleDeskChange(desk.id, 'systemPrompt', e.target.value)}
                                    />
                                </div>

                                <div className="space-y-2">
                                    <label className="text-[10px] font-mono text-gray-500 uppercase">问候语 (Greeting Message)</label>
                                    <input
                                        className="w-full bg-gray-950 border border-gray-800 rounded-xl p-3 text-sm text-gray-400 focus:border-gray-600 outline-none"
                                        value={desk.greeting || ''}
                                        onChange={e => handleDeskChange(desk.id, 'greeting', e.target.value)}
                                    />
                                </div>

                                <div className="space-y-2">
                                    <label className="text-[10px] font-mono text-gray-500 uppercase">工作时间 (Working Hours)</label>
                                    <input
                                        className="w-full bg-gray-950 border border-gray-800 rounded-xl p-3 text-sm text-gray-400 focus:border-gray-600 outline-none"
                                        value={desk.workingHours || ''}
                                        placeholder="如：9:00-18:00"
                                        onChange={e => handleDeskChange(desk.id, 'workingHours', e.target.value)}
                                    />
                                </div>

                                <div className="space-y-4 pt-4 border-t border-gray-800">
                                    <label className="text-[10px] font-mono text-gray-500 uppercase flex items-center gap-2">
                                        坐标位置 (POSITION)
                                        <span className="text-[9px] bg-cyan-500/10 text-cyan-400 px-1.5 py-0.5 rounded border border-cyan-500/20 lowercase font-normal italic">
                                            fixed_pos
                                        </span>
                                    </label>
                                    <div className="flex flex-wrap items-center gap-6 bg-gray-950/50 p-4 rounded-xl border border-gray-800/50">
                                        <div className="flex items-center gap-4">
                                            <div className="flex items-center gap-2">
                                                <span className="text-xs font-mono text-gray-500">X:</span>
                                                <input
                                                    type="number"
                                                    className="w-24 bg-gray-950 border border-gray-800 rounded-lg p-2 text-sm text-cyan-400 font-mono focus:border-cyan-500 outline-none"
                                                    value={desk.x || 0}
                                                    onChange={e => handleDeskChange(desk.id, 'x', parseInt(e.target.value) || 0)}
                                                />
                                            </div>
                                            <div className="flex items-center gap-2">
                                                <span className="text-xs font-mono text-gray-500">Y:</span>
                                                <input
                                                    type="number"
                                                    className="w-24 bg-gray-950 border border-gray-800 rounded-lg p-2 text-sm text-cyan-400 font-mono focus:border-cyan-500 outline-none"
                                                    value={desk.y || 0}
                                                    onChange={e => handleDeskChange(desk.id, 'y', parseInt(e.target.value) || 0)}
                                                />
                                            </div>
                                        </div>

                                        <p className="text-[10px] text-gray-600 italic sm:ml-auto">
                                            * 前台客服在地图上的固定位置坐标。
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            )}

            {status && (
                <div className="fixed bottom-10 right-10 bg-gray-900 border border-purple-500/50 text-white px-6 py-4 rounded-2xl shadow-2xl flex items-center gap-3 z-50 animate-in fade-in slide-in-from-bottom-4 duration-300">
                    <div className="w-2 h-2 bg-purple-500 rounded-full animate-ping"></div>
                    <span className="text-sm font-medium">{status}</span>
                </div>
            )}
        </div>
    )
}
